apiVersion: v1
kind: Namespace
metadata:
  name: trafficserver-test

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: trafficserver-test
  name: trafficserver-test
  namespace: trafficserver-test
spec:
  minReadySeconds: 30

  selector:
    matchLabels:
      app: trafficserver-test

  # Run two copies, for redundancy.
  replicas: 1

  template:
    metadata:
      labels:
        app: trafficserver-test
    spec:

      containers:
        - name: trafficserver-test
          image: ats_centos7_test:latest
          imagePullPolicy: IfNotPresent

          ports:
          - containerPort: 8080
            hostPort: 8080
            name: http
            protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: trafficserver-test
  namespace: trafficserver-test
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31080
  selector:
    app: trafficserver-test
